### ISSUE TITLE
TBD

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#1]
The target of this project is wherever one or more of the following:
- [ ] create an overview/matrix: 
  - [ ] which Providers have a good quality (generation time, valid data, ...)
  - [ ] use different UA databases to generate those matrixes
- [ ] maybe release this as a counter part for UA parsing, like https://github.com/geocoder-php/Geocoder

...for now it's just a prototype:
- install it with composer
- execute `php tests/test.php` for the matrix

//cc @sgiehl could i use the `Piwik-DeviceDetector` fixtures (https://github.com/piwik/device-detector/tree/master/Tests/fixtures) to generate matrix with all provider results?

**Comment by sgiehl** [comment]
sure, feel free to do so.

**Comment by ThaDafinser** [comment]
Thank you @sgiehl
