### ISSUE TITLE
New provider: wurfl

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#10]
https://github.com/sam-media/wurfl-api

or

https://github.com/mimmi20/Wurfl

**Comment by mimmi20** [comment]
These providers work only if you have an `wurfl.xml` file. This was free until 2-3 years ago. You may find it here (https://github.com/fauvel/wurfl-dbapi/blob/master/data/wurfl.xml), but you should not commit it to your repo.

**Comment by mimmi20** [comment]
My version of Wurfl is namespaced, the other not.

**Comment by ThaDafinser** [comment]
@mimmi20 i added a prototype here: https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/Wurfl.php

You can also try it out here: http://useragent.mkf.solutions/

Todos:
- [x] complete unitTests
- [x] remove "defaults"
- [x] complete raw result
- [x] get feedback if all is correct

**Comment by mimmi20** [comment]
@ThaDafinser With a little mapping it should be possible to detectg the device type. I dont know if the `form_factor` property was already added in this version.

**Comment by mimmi20** [comment]
Your implementation looks fine.

**Comment by ThaDafinser** [comment]
Thank you. I added the `form_factor` .

It's also tested completely now
