### ISSUE TITLE
New Provider: nfriedly/whatsmyua.com

### ISSUE THREAD

**Issue by mimmi20** [ThaDafinser/UserAgentParser#106]
see https://github.com/nfriedly/whatsmyua.com

**Comment by ThaDafinser** [comment]
@mimmi20 thank you, but i don't fine the actual code there.

It seems to be JS code and (partly?) based on https://github.com/tobie/ua-parser (the PHP project of this we got already called UAParser)

**Comment by mimmi20** [comment]
@ThaDafinser I didn't look too much in it. Sorry.
