### ISSUE TITLE
Nice dumper

### ISSUE THREAD

**Issue by serhiime** [ThaDafinser/UserAgentParser#108]
You can try to add nice dumper (https://packagist.org/packages/raulfraile/ladybug)  for your live demonstration: http://useragent.mkf.solutions/

**Comment by ThaDafinser** [comment]
@endorphinua thank you for the suggestion.

A highlighter would be a good improvement, but i would more likely do it on the client side.
E.g. something like http://prismjs.com/

**Comment by serhiime** [comment]
Ok ) Thanx for response.
