### ISSUE TITLE
This package requires thadafinser/package-info but does not appear to use it.

### ISSUE THREAD

**Issue by unstoppablecarl** [ThaDafinser/UserAgentParser#114]
This package requires `thadafinser/package-info` but does not appear to use it. Am I missing something?

**Comment by ThaDafinser** [comment]
@unstoppablecarl its used indirectly. During installation it extracts the versions of the installed packages.

That information is then used here: 
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/AbstractProvider.php#L123-L132
