### ISSUE TITLE
PHP7 failure from whichbrowser

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#12]
@NielsLeenheer i added now unitTests for all providers, but `WhichBrowser` fails on PHP7.

I excluded now PHP7 temporary, that the tests can pass here.

Do you have any plans for PHP7 compability?
https://travis-ci.org/ThaDafinser/UserAgentParser/jobs/90565282#L284

**Comment by NielsLeenheer** [comment]
Yes, absolutely. WhichBrowser will be PHP7 compatible, start using namespace and a proper PHP api.

**Comment by NielsLeenheer** [comment]
PHP 7 compatibility was just a simple issue. Release 1.0.1037 should work on PHP 7.

**Comment by ThaDafinser** [comment]
Thank you. I will grad it today in the afternoon and check it

**Comment by ThaDafinser** [comment]
Works again in the latest build. Thank you for the fast update

https://travis-ci.org/ThaDafinser/UserAgentParser/jobs/90711821
