### ISSUE TITLE
Final check Browscap

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#13]
Hello @mimmi20 (sorry to ping again)

i start now to finalize the BrowscapPhp provider.

Could you maybe check if i missed here something, or done something wrong in the implementation?
https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/BrowscapPhp.php

For testing i create a small `browscap.ini` file and used it in the tests.
https://github.com/ThaDafinser/UserAgentParser/blob/master/tests/fixtures/browscap.ini

Is this fine or do i need to mock i further?
https://github.com/ThaDafinser/UserAgentParser/blob/master/tests/unit/Provider/BrowscapPhpTest.php#L41

**Comment by ThaDafinser** [comment]
Last note: The unitTests are not finished, since i was not sure if the mocking is good this way and i want this "clean" first.

**Comment by mimmi20** [comment]
@ThaDafinser On line 148/149 I dont understand why do you check for a version, but dont add it to your Model. I asume this should the same as the line 169-179. You should handle this lines independed of the `Bot` status.
The ini file you created is ok, but not really needed. You should mock as much as possible.

**Comment by ThaDafinser** [comment]
Thank you for the feedback.

> On line 148/149 I dont understand why do you check for a version, but dont add it to your Model

That was a copy paste error, which i fixed now
https://github.com/ThaDafinser/UserAgentParser/commit/2cb2ad5edb061457fbc073b0ade7fb4b06c8613b

> The ini file you created is ok, but not really needed. You should mock as much as possible.

You are right. I will mock the parser result completely, so the test will also be faster.

**Comment by ThaDafinser** [comment]
Tests are now mocked.

If there are other changed, feel free to open a new issue.

Thank you so far for  the help!

https://github.com/ThaDafinser/UserAgentParser/blob/master/tests/unit/Provider/BrowscapPhpTest.php#L15
