### ISSUE TITLE
New provider: mimmi20/BrowserDetector

### ISSUE THREAD

**Issue by mimmi20** [ThaDafinser/UserAgentParser#16]
Repo-Url: https://github.com/mimmi20/BrowserDetector

**Comment by ThaDafinser** [comment]
@mimmi20 how stable is this package? Does it use Wurfl as the datasource?

**Comment by mimmi20** [comment]
I did not create a tag yet. I use some aditional data from Wurfl, but not the data you use in your comparasation.

**Comment by ThaDafinser** [comment]
Just ping me, when your package is ready.

**Comment by ThaDafinser** [comment]
@mimmi20 do you have currently a target date for the "v1"?

**Comment by mimmi20** [comment]
I hope to be ready next month. Actually I have issues with a version library I included last month.

**Comment by mimmi20** [comment]
@ThaDafinser Its stable now.

**Comment by ThaDafinser** [comment]
@mimmi20 great! Could you please write a short guide in the readme, how to use it correctly?

In general it looks like straight forward, but not that i forget something :+1: 
https://github.com/mimmi20/BrowserDetector/blob/master/tests/DetectorTest.php#L44-L67

**Comment by mimmi20** [comment]
I updated the readme.

**Comment by ThaDafinser** [comment]
Thanks. My local PR is quiet good already. Need todo some testing and then will publish him

**Comment by mimmi20** [comment]
My actual test cases you can find here: https://github.com/mimmi20/browser-detector-tests (around 200.000 useragents). More useragents you could find here: https://github.com/mimmi20/ua-comparator (~2.000.000).
