### ISSUE TITLE
First results - comparing some vendors

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#2]
Hello together,

i create this **prototype** project in order to try out the different UserAgent parsers available for PHP.

First i wanted to try if it's currently possible to create an abstract result set, like it's done for GeoIP already https://github.com/geocoder-php/Geocoder
Second i wanted to have a Chain Adapter on top it to get results from different vendors to get better results https://github.com/ThaDafinser/UserAgentParser/blob/master/bin/generateMatrix.php#L45-L53

Last but not least i wanted to compare the different implementations - how complete and good are they?

At this stage the results of the comparison are not completed, since some vendor adapter will be not complete or have errors.
But i still wanted to share those results to you all, to get (hopefully) some feedback about your Adapter implementation and get improvements https://github.com/ThaDafinser/UserAgentParser/tree/master/src/Provider
## See the (current not correct or complete) results

Download the HTML files from here and open it just in a browser https://github.com/ThaDafinser/UserAgentParser/tree/master/data/results

It should look like this screenshot.
Click on "toggle" to see the original data and the result detail

![image](https://cloud.githubusercontent.com/assets/533017/10972816/23000960-83db-11e5-9a7f-507b1b5a4494.png)
### Note about used datasets to generate the matrix

I currently did not used datasets from each vendor, so the comparison is not fair currently. (and of course missing convertions or errors)
- [ ] [browscap/browscap-php](https://github.com/browscap/browscap-php) the resources have placeholders...need to check how they can we replaced accordingly [example file](https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/access-netfront/access-netfront-2-0-3-5.json)
- [x] [donatj/phpuseragentparser](https://github.com/donatj/PhpUserAgent)
- [x] [piwik/device-detector](https://github.com/piwik/device-detector)
- [ ] [ua-parser/uap-php](https://github.com/ua-parser/uap-php) waiting for a release https://github.com/ua-parser/uap-core/issues/114
- [ ] [whichbrowser/whichbrowser](https://github.com/WhichBrowser/WhichBrowser) found no test data list.
- [ ] [woothee/woothee](https://github.com/woothee/woothee-php) waiting for a release https://github.com/woothee/woothee/issues/19
- [x] [yzalis/ua-parser](https://github.com/yzalis/UAParser)

Better would be an additional independent list...need to find a good source first
## Next steps
- [ ] get some feedback, about the provider adapter
- [ ] complete and correct the provider adapters to get better results and a true comparison
- [ ] refactor all code...it's ugly written...just a prototype
- [ ] seperate UserAgentParser and the Matrix generation
- [ ] release initial UserAgentParser
- [ ] add more test datasets for the matrix
- [ ] create a better comparison markup...the current on is not so "nice"
- [ ] release a Matrix generator website

I hope it's ok to ping you all ...if not just tell me and i wont do it again :+1: 
@mimmi20
@donatj
@sgiehl
@lstrojny 
@NielsLeenheer
@yuya-takeyama
@blaugueux

**Comment by donatj** [comment]
The big advantage to mine - parse time an order of magnitude quicker than the others :smile: 

I just noticed OS is never filled in my results, but I provide OS, just not OS version. A bug in your test?

**Comment by donatj** [comment]
I just noticed OS is never filled in my results, but I provide OS, just not OS version.

**Comment by ThaDafinser** [comment]
@donatj every parser here has it's eligibility, it just depends on the goal you want to achieve with a UA analyisation.

I didn't include OS, since it was mixed with device informations, see here: https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/DonatjUAParser.php#L17-L18

**Comment by mimmi20** [comment]
@ThaDafinser The resources of the browscap parser are not meant to be used directly. These rules are parsed together into ini files and have the format designed for PHPs get_gebrowser function. The browscap-php library can handle this and parses the rules into regexes who are tested against the useragent.

Do you need more feedback?

**Comment by mimmi20** [comment]
@ThaDafinser If you find a useragant who is not detected correctly, be free to open an issue in the browscap/browscap project.

**Comment by NielsLeenheer** [comment]
Very interesting project!

I must first say that WhichBrowser currently isn't designed to be used directly from PHP. It does server side detection, but exposes a JavaScript API in the browser. So calling it directly from PHP is certainly possible, but it might be a bit iffy.

I'll create a pull request from some improvements to the WhichBrowser adapter later today (I hope).

I also have a test suite that you are free to incorporate into this project, but at the moment it is in a separate git branch and not part of the composer distribution. There are a bunch of Yaml files and containing a number of headers (including User-Agent) and the results I expect. But it would be fairly trivial to strip all of that out and get a list of ua strings: https://github.com/WhichBrowser/WhichBrowser/tree/dev/tests

**Comment by ThaDafinser** [comment]
@NielsLeenheer i have a completely rewriten all of  the adapters localy. I will push them later this weekend so you can grab the updates.

I will try to include the testsuite in this case with the next update i will make in a seperate branch.

If you feel that its not good to include it as a server side adapter i will remote it, that nobody expect good results like the "good" one as a JS include provides them

**Comment by NielsLeenheer** [comment]
@ThaDafinser The code for doing the comparisons seems to have disappeared? Is that still part of the scope of this project? Is it coming back?

**Comment by ThaDafinser** [comment]
@NielsLeenheer you need to use the v0.0.1 https://github.com/ThaDafinser/UserAgentParser/tree/v0.0.1

I will release a new package under the the name https://github.com/ThaDafinser/UserAgentParserMatrix soon

I think a split is better, since this can be used without the matrix

**Comment by NielsLeenheer** [comment]
@ThaDafinser Ok, makes sense.

**Comment by ThaDafinser** [comment]
Moving to https://github.com/ThaDafinser/UserAgentParserComparison/issues/1
