### ISSUE TITLE
More generics for various Providers

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParser#37]
BrowscapPhp:
- model: "Windows Desktop"
- model: "Linux Desktop"

SinergiBrowserDetector:
- model: "Windows Phone"

Wurfl:
- model: "SmartTV"
- browser: "Java Applet"

**Comment by ThaDafinser** [comment]
Thank you. I will try to get into this soon. Quiet busy this week.

**Comment by ThaDafinser** [comment]
Most should be cleared already.

Found those with this query

``` SQL
SELECT * FROM `user-agent-parser-comparison`.result
join provider on proId = provider_id
where
    provider_id IN(
        SELECT
            proId
        FROM provider
        WHERE proType = 'real'
    )
 AND (
 resDeviceModel LIKE "%Windows%"
 or  resDeviceModel LIKE "%Unix%"
 or  resDeviceModel LIKE "%SmartTV%"
 )
```

smartTV PiwikDeviceDetector
SmartTV PiwikDeviceDetector
SmartTV PiwikDeviceDetector
smartTV UAParser
SmartTV2012 UAParser
SmartTV2013 UAParser
SmartTV2013 UAParser
SmartTV2013 UAParser
SmartTV2013 UAParser
SmartTV2013 UAParser
SmartTV2014 UAParser
SmartTV2015 UAParser
TV-SMARTTV-500  UAParser
Unix7   PiwikDeviceDetector
Unix7   UAParser
Unix7   WhichBrowser
Windows PiwikDeviceDetector
Windows PiwikDeviceDetector
Windows PiwikDeviceDetector
Windows Mobile GPS  WhichBrowser
Windows Phone   PiwikDeviceDetector
Windows Phone - Internet 7  UAParser
Windows Phone 8 / HTC Mozart    UAParser
Windows Phone 8S by HTC PiwikDeviceDetector
Windows Phone 8S by HTC PiwikDeviceDetector
Windows Phone 8S by HTC PiwikDeviceDetector
Windows Phone 8S By HTC PiwikDeviceDetector
Windows Phone 8S by HTC PiwikDeviceDetector
Windows Phone 8S by HTC UAParser
Windows Phone 8S by HTC UAParser
Windows Phone 8S by HTC UAParser
Windows Phone 8S By HTC UAParser
Windows Phone 8S by HTC UAParser
Windows Phone 8S by HTC UAParser
Windows Phone 8S by HTC WhichBrowser
Windows Phone 8X    BrowscapPhp
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC PiwikDeviceDetector
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC UAParser
Windows Phone 8X by HTC WhichBrowser
Windows Phone 8X by HTC-H0002   PiwikDeviceDetector
Windows Phone 8Xby HTC  PiwikDeviceDetector
Windows Phone 8Xby HTC  UAParser
Windows_Phone_8X_by_HTC-H0002   UAParser
WindowsPhone8Xby    PiwikDeviceDetector
WindowsPhone8Xby    UAParserTC
UAParser    Windows Phone 8S by HTC
WhichBrowser    Windows Phone 8S by HTC
BrowscapPhp Windows Phone 8X
PiwikDeviceDetector Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
UAParser    Windows Phone 8X by HTC
WhichBrowser    Windows Phone 8X by HTC
PiwikDeviceDetector Windows Phone 8X by HTC-H0002
PiwikDeviceDetector Windows Phone 8Xby HTC
UAParser    Windows Phone 8Xby HTC
UAParser    Windows_Phone_8X_by_HTC-H0002
PiwikDeviceDetector WindowsPhone8Xby
UAParser    WindowsPhone8Xby

**Comment by ThaDafinser** [comment]
@NielsLeenheer i close this for now.

If we find new one, let's create an issue per provider for it
