### ISSUE TITLE
New provider: zsxsoft/php-useragent

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/UserAgentParser#49]
https://github.com/zsxsoft/php-useragent

**Comment by ThaDafinser** [comment]
The data is sadly not splitted in the way, we would need it.
- Browser name + version is in one field (needed in 2 different fields)
- OS name + version and device name + version information is in one field (needed in 4 different fields)

https://github.com/zsxsoft/php-useragent/blob/master/tests/TestUserAgent.php#L301-L302

So it's not possible at the moment, to include it here.

@zsxsoft is there any intention to change this in the near future? Otherwise i will close this as invalid

**Comment by zsxsoft** [comment]
WTF!
In my memory I have done it! But I realized that I forgot it just now...

I will do it ASAP.

**Comment by ThaDafinser** [comment]
Cool thing :+1: 

If you manage to split it until the 20th March, i can also include your lib in the next comparison round
https://github.com/ThaDafinser/UserAgentParserComparison/issues/16#issuecomment-188123125

**Comment by zsxsoft** [comment]
Have done. :)

**Comment by ThaDafinser** [comment]
@zsxsoft i will try it this week. Is it already stable - can you create already a release?

**Comment by zsxsoft** [comment]
I think it should be done at this Saturday.

Sent from Outlook Mobile

On Sun, Mar 6, 2016 at 11:43 PM -0800, "Martin Keckeis" notifications@github.com wrote:

@zsxsoft i will try it this week. Is it already stable - can you create already a release?

---

**Comment by ThaDafinser** [comment]
PR ready #63

**Comment by ThaDafinser** [comment]
Implemented https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/Zsxsoft.php
