### ISSUE TITLE
Add tests from WhichBrowser

### ISSUE THREAD

**Issue by NielsLeenheer** [ThaDafinser/UserAgentParser#6]
I've created a separate Composer package the tests I run for WhichBrowser. The package is called `whichbrowser/testrunner` and includes the runner.php script and all the yaml files. It is automatically updated whenever there is a new release of WhichBrowser.

If you want I can probably create a pull request for the actual extracting of the UA strings.

But it is also possible to extract it by using the runner.php script from the command line:

`php vendor/whichbrowser/testrunner/runner.php list`

or

`php vendor/whichbrowser/testrunner/runner.php list television`

or

`php vendor/whichbrowser/testrunner/runner.php list mobile tablet television gaming`

**Comment by ThaDafinser** [comment]
@NielsLeenheer thank you. I will look into it today and check now far i get in the new packages 
https://github.com/ThaDafinser/UserAgentParserMatrix

**Comment by ThaDafinser** [comment]
@NielsLeenheer they are included now here: https://github.com/ThaDafinser/UserAgentParserMatrix/tree/master/data/datasets

The results are also available here: https://github.com/ThaDafinser/UserAgentParserMatrix/tree/master/data/results
