### ISSUE TITLE
New Provider: crossjoin/Browscap

### ISSUE THREAD

**Issue by mimmi20** [ThaDafinser/UserAgentParser#70]
crossjoin/Browscap is a UA parser, who uses the browscap.ini too, but is faster and requires lower amout of RAM. Actually only a file cache is supported. The browscap-php library has adopted a lot of features from it.

**Comment by ThaDafinser** [comment]
https://github.com/crossjoin/Browscap

Maybe a package like this could contain an alternative implentation
https://github.com/geocoder-php/geocoder-extra

Or we leave it together here. Dunno if the split is really a good idea

**Comment by ThaDafinser** [comment]
I wait currently for the tested version, then i check again if we implement this parser
https://github.com/crossjoin/Browscap/issues/19#issuecomment-203470717
