### ISSUE TITLE
PiwikDeviceDetector Provider error

### ISSUE THREAD

**Issue by simtabi** [ThaDafinser/UserAgentParser#77]
Hi, 
I a using the latest version of this library. Now theres an issue. Not sure if its a bug.
I already have this library installed `PiwikDeviceDetector` but i keep getting the following exception error. `You need to install the package piwik/device-detector to use this provider`. I have done all i could to debug but i can seem to find a solution. The only one is to comment out the following:
    public function __construct(DeviceDetector $parser = null)

```
    {
        if ($parser === null && ! file_exists('vendor/' . $this->getPackageName() . '/composer.json')) {
         Icommented this line - // throw new PackageNotLoadedException('You need to install the package ' . $this->getPackageName() . ' to use this provider');
        }

        $this->parser = $parser;
    }
```

I moved the requested library into the `vendor/` directory as its supposed to, but it didn't solve either.

I am on windows and it doesn't allow this kind of file naming structure `piwik/device-detector`, because i believe this is the directory that is being looked, and since it can not be located, an error is thrown.

Any suggestions?

**Comment by ThaDafinser** [comment]
he ho @SimTabi :smile: 

It seems you have not installed the two packages with https://getcomposer.org/

Currently that is the only supported way to install this package. Otherwise you need to uncomment that check like you mentioned above.

A bit releated to #61 (custom vendor directory with composer)

**Comment by ThaDafinser** [comment]
> I am on windows and it doesn't allow this kind of file naming structure piwik/device-detector

@SimTabi i'm on windows as well - that work. Those are 2 seperate directories (maybe then you get it working without composer)
