### ISSUE TITLE
composer autoload issue

### ISSUE THREAD

**Issue by itsonit** [ThaDafinser/UserAgentParser#89]
If the running script is placed in a a subdirectory, it will break the loading of the installed providers.

For ex., including autoload like this
`require __DIR__.'../vendor/autoload.php';`

produce a fatal error:

`PHP Fatal error:  Uncaught exception 'UserAgentParser\\Exception\\PackageNotLoadedException' with message 'You need to install the package piwik/device-detector to use this provider' in ..`

**Comment by ThaDafinser** [comment]
@itsonit see related issue https://github.com/ThaDafinser/UserAgentParser/issues/61#issuecomment-205305981

Will be solved when moving to php7 only in the next major. For now

**Comment by ThaDafinser** [comment]
For now you need to disable this check. Because the folder is not correctly "relative"

**Comment by itsonit** [comment]
thx for your reply. For my purpose it was simple to switch routing from filesystem to programmatic aka url-rewrite.

**Comment by ThaDafinser** [comment]
Nice you found already a workaround :+1:

**Comment by egorsmkv** [comment]
@ThaDafinser  Faced with this problem right now. Can you fix this bug?

**Comment by ThaDafinser** [comment]
@egorsmkv can you show me your directory structure and give more informations?

**Comment by egorsmkv** [comment]
@ThaDafinser I add your library to my Yii2 project and get this error.

**Comment by ThaDafinser** [comment]
@egorsmkv you can do a `var_dump(getcwd()); exit()` right before the Exception is thrown?

**Comment by ThaDafinser** [comment]
I think this could work

``` php
if (! file_exists(__DIR__ . '/../../../../' . $this->getPackageName() . '/composer.json') && ! file_exists(__DIR__ . '/../../vendor/' . $this->getPackageName() . '/composer.json')) {
    throw new PackageNotLoadedException('You need to install the package ' . $this->getPackageName() . ' to use this provider');
}
```

**Comment by egorsmkv** [comment]
the fact is that I do not want to put the crutches in the code

**Comment by ThaDafinser** [comment]
@egorsmkv i asked you for your directory structure and i asked if you could post the output of a debug statement.

If you dont want to give me any information i will stop trying to solve this issue

//note the comment above "I think this could work..." is a side note for a possible fix

**Comment by egorsmkv** [comment]
@ThaDafinser basic yii2 structure: https://github.com/yiisoft/yii2-app-basic#directory-structure

Maybe it's worth to check availability of the library through the `try / catch`?

**Comment by ThaDafinser** [comment]
I found this solution...
https://github.com/mindplay-dk/composer-locator

Need to create a PR soon.

**Comment by ThaDafinser** [comment]
@itsonit @egorsmkv this issue should be fixed now.

Please try out `dev-master` and tell me if it works `composer require thadafinser/user-agent-parser:dev-master`

https://github.com/ThaDafinser/UserAgentParser/pull/99

**Comment by ThaDafinser** [comment]
//cc to all forks, which corrected this issue - please try out the latest master :smile: 

@cedricalfonsi @aurelijusrozenas @palpalani @kallaikoi

**Comment by chris-doehring** [comment]
@ThaDafinser When do you plan to release a new version which includes this fix?

**Comment by ThaDafinser** [comment]
@chris-doehring i'm just waiting for a feedback, from 1 or 2 people...

**Comment by egorsmkv** [comment]
@ThaDafinser unfortunately, I don't use this library, so I can't test the change.

**Comment by chris-doehring** [comment]
@ThaDafinser I tried version 1.4.0 and got the same issue as described above. The current dev-master does fix the issue.

**Comment by aurelijusrozenas** [comment]
Yes, seems to be working. Tested on symfony 2.8.

**Comment by ThaDafinser** [comment]
Release `v1.5.0` https://github.com/ThaDafinser/UserAgentParser/releases/tag/v1.5.0
